import type { TimelineTemplate } from '@/types';

// Built-in project timeline templates.
// Each template defines a set of phases and milestones positioned relative
// to a "timeline start" date (chosen at apply-time). Dates are stored as
// offsets in days so templates can be dropped onto any start date.

export const TIMELINE_TEMPLATES: TimelineTemplate[] = [
    {
        id: 'website_build',
        name: 'Website Build',
        description: 'Discovery, design, build, QA, and launch for a standard marketing site.',
        icon: '🌐',
        phases: [
            { title: 'Discovery', color: 'violet', order: 0 },
            { title: 'Design', color: 'blue', order: 1 },
            { title: 'Build', color: 'emerald', order: 2 },
            { title: 'Launch', color: 'amber', order: 3 },
        ],
        milestones: [
            {
                title: 'Kickoff & requirements',
                status: 'not_started',
                phaseIndex: 0,
                startDate: '',
                endDate: '',
                startOffsetDays: 0,
                durationDays: 5,
                order: 0,
            },
            {
                title: 'Research & inspiration',
                status: 'not_started',
                phaseIndex: 0,
                startDate: '',
                endDate: '',
                startOffsetDays: 3,
                durationDays: 7,
                order: 1,
            },
            {
                title: 'Wireframes',
                status: 'not_started',
                phaseIndex: 1,
                startDate: '',
                endDate: '',
                startOffsetDays: 10,
                durationDays: 8,
                order: 2,
            },
            {
                title: 'Visual design',
                status: 'not_started',
                phaseIndex: 1,
                startDate: '',
                endDate: '',
                startOffsetDays: 16,
                durationDays: 10,
                order: 3,
            },
            {
                title: 'Development sprint',
                status: 'not_started',
                phaseIndex: 2,
                startDate: '',
                endDate: '',
                startOffsetDays: 24,
                durationDays: 14,
                order: 4,
            },
            {
                title: 'QA & revisions',
                status: 'not_started',
                phaseIndex: 2,
                startDate: '',
                endDate: '',
                startOffsetDays: 36,
                durationDays: 7,
                order: 5,
            },
            {
                title: 'Launch',
                status: 'not_started',
                phaseIndex: 3,
                startDate: '',
                endDate: '',
                startOffsetDays: 43,
                durationDays: 3,
                order: 6,
            },
        ],
    },
    {
        id: 'content_launch',
        name: 'Content Launch',
        description: 'Plan, write, review, and ship a campaign or content drop.',
        icon: '✍️',
        phases: [
            { title: 'Plan', color: 'blue', order: 0 },
            { title: 'Produce', color: 'emerald', order: 1 },
            { title: 'Ship', color: 'rose', order: 2 },
        ],
        milestones: [
            {
                title: 'Topic brief',
                status: 'not_started',
                phaseIndex: 0,
                startDate: '',
                endDate: '',
                startOffsetDays: 0,
                durationDays: 2,
                order: 0,
            },
            {
                title: 'Outline',
                status: 'not_started',
                phaseIndex: 0,
                startDate: '',
                endDate: '',
                startOffsetDays: 2,
                durationDays: 2,
                order: 1,
            },
            {
                title: 'First draft',
                status: 'not_started',
                phaseIndex: 1,
                startDate: '',
                endDate: '',
                startOffsetDays: 4,
                durationDays: 5,
                order: 2,
            },
            {
                title: 'Review & edits',
                status: 'not_started',
                phaseIndex: 1,
                startDate: '',
                endDate: '',
                startOffsetDays: 9,
                durationDays: 3,
                order: 3,
            },
            {
                title: 'Visual assets',
                status: 'not_started',
                phaseIndex: 1,
                startDate: '',
                endDate: '',
                startOffsetDays: 7,
                durationDays: 4,
                order: 4,
            },
            {
                title: 'Publish & promote',
                status: 'not_started',
                phaseIndex: 2,
                startDate: '',
                endDate: '',
                startOffsetDays: 12,
                durationDays: 3,
                order: 5,
            },
        ],
    },
    {
        id: 'webflow_migration',
        name: 'Webflow Migration',
        description: 'Move an existing site onto Webflow with content, SEO, and launch checks.',
        icon: '🧱',
        phases: [
            { title: 'Audit', color: 'violet', order: 0 },
            { title: 'Rebuild', color: 'blue', order: 1 },
            { title: 'Migrate', color: 'emerald', order: 2 },
            { title: 'Cutover', color: 'amber', order: 3 },
        ],
        milestones: [
            {
                title: 'Site audit',
                status: 'not_started',
                phaseIndex: 0,
                startDate: '',
                endDate: '',
                startOffsetDays: 0,
                durationDays: 4,
                order: 0,
            },
            {
                title: 'Sitemap + redirects plan',
                status: 'not_started',
                phaseIndex: 0,
                startDate: '',
                endDate: '',
                startOffsetDays: 2,
                durationDays: 4,
                order: 1,
            },
            {
                title: 'Rebuild templates',
                status: 'not_started',
                phaseIndex: 1,
                startDate: '',
                endDate: '',
                startOffsetDays: 6,
                durationDays: 12,
                order: 2,
            },
            {
                title: 'Content migration',
                status: 'not_started',
                phaseIndex: 2,
                startDate: '',
                endDate: '',
                startOffsetDays: 14,
                durationDays: 9,
                order: 3,
            },
            {
                title: 'QA & SEO sweep',
                status: 'not_started',
                phaseIndex: 3,
                startDate: '',
                endDate: '',
                startOffsetDays: 23,
                durationDays: 5,
                order: 4,
            },
            {
                title: 'DNS cutover',
                status: 'not_started',
                phaseIndex: 3,
                startDate: '',
                endDate: '',
                startOffsetDays: 28,
                durationDays: 2,
                order: 5,
            },
        ],
    },
];

export function getTimelineTemplate(id: string): TimelineTemplate | undefined {
    return TIMELINE_TEMPLATES.find((t) => t.id === id);
}
