/**
 * Local ALT text generator using Ollama (Gemma 3 4B multimodal).
 * No API key required. Requires a running Ollama instance at OLLAMA_HOST
 * (defaults to http://localhost:11434) with the model pulled, e.g.:
 *
 *   ollama pull gemma3:4b
 */

import type { CmsImageEntry, CmsAltSuggestion } from '@/types/webflow';

const DEFAULT_HOST = 'http://localhost:11434';
const DEFAULT_MODEL = 'gemma3:4b';

function cleanFileName(name: string): string {
  return name.replace(/\.[^.]+$/, '').replace(/[-_]/g, ' ').replace(/\s+/g, ' ').trim();
}

export function fallbackAlt(entry: Pick<CmsImageEntry, 'imageUrl'>): string {
  const filename = entry.imageUrl.split('/').pop() || '';
  return cleanFileName(filename).slice(0, 125) || 'Image';
}

function buildPrompt(entry: CmsImageEntry, siteName?: string): string {
  const siteContext = siteName
    ? `This image is from the ${siteName} website.`
    : 'This image is from a business website.';
  return `${siteContext}
Context — Collection: ${entry.collectionName} · Item: ${entry.itemName} · Field: ${entry.fieldDisplayName}

Write ONE short alt-text sentence describing what is visible in the image.

Rules:
- 5 to 18 words, never more than 125 characters.
- Do NOT begin with "Image of", "Picture of", "Photo of".
- Neutral, factual English.
- If it is clearly a headshot and the item name looks like a person's name, start with that name.
- If it is a logo, reply "[Organization] logo".
- If it is purely decorative with no content, reply with an empty string.
- Output ONLY the alt text. No quotes, no explanation.`;
}

async function fetchImageBase64(url: string): Promise<string> {
  const res = await fetch(url, { headers: { 'User-Agent': 'cms-alt/1.0' } });
  if (!res.ok) throw new Error(`image fetch failed: ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  return buf.toString('base64');
}

async function generateOne(
  entry: CmsImageEntry,
  options: { host: string; model: string; siteName?: string }
): Promise<string | null> {
  const base64 = await fetchImageBase64(entry.imageUrl);
  const res = await fetch(`${options.host}/api/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: options.model,
      prompt: buildPrompt(entry, options.siteName),
      images: [base64],
      stream: false,
      options: { temperature: 0.2, num_predict: 80 },
    }),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`ollama ${res.status}: ${text.slice(0, 200)}`);
  }
  const data = (await res.json()) as { response?: string };
  const raw = (data.response || '').trim();
  // Strip wrapping quotes/backticks
  const cleaned = raw.replace(/^["'`]+|["'`]+$/g, '').trim();
  if (!cleaned) return '';
  // Enforce 125-char limit
  return cleaned.slice(0, 125);
}

async function pMap<T, R>(
  items: T[],
  concurrency: number,
  fn: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  const workers = Array.from({ length: Math.min(concurrency, items.length) }, async () => {
    while (true) {
      const i = next++;
      if (i >= items.length) break;
      results[i] = await fn(items[i], i);
    }
  });
  await Promise.all(workers);
  return results;
}

export async function generateAltForImages(
  entries: CmsImageEntry[],
  options: { host?: string; model?: string; siteName?: string; concurrency?: number } = {}
): Promise<CmsAltSuggestion[]> {
  const targets = entries.slice(0, 100);
  const host = options.host || process.env.OLLAMA_HOST || DEFAULT_HOST;
  const model = options.model || process.env.OLLAMA_MODEL || DEFAULT_MODEL;
  const concurrency = options.concurrency ?? 3;

  return pMap(targets, concurrency, async entry => {
    try {
      const alt = await generateOne(entry, { host, model, siteName: options.siteName });
      if (alt == null) {
        return {
          entryId: entry.id,
          altText: fallbackAlt(entry),
          reason: 'Fallback from filename (empty response)',
        };
      }
      return {
        entryId: entry.id,
        altText: alt,
        reason: `Generated by ${model}`,
      };
    } catch (err) {
      return {
        entryId: entry.id,
        altText: fallbackAlt(entry),
        reason: `Fallback — ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  });
}
